# Generated by Django 6.0.4 on 2026-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='Ijaraga berildi'),
        ),
        migrations.AddField(
            model_name='house',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
