# Generated by Django 6.0.4 on 2026-05-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_is_rented_house_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
